matrix:
  include:
    - os: osx
      osx_image: xcode10.2

    - os: linux
      dist: trusty

cache:
  directories:
    - $HOME/texlive
    - $HOME/.texlive
    - $HOME/texmf

sudo: false

language: generic

install:
  - . ./install-tex.sh

script:
  - latex -v
  - tlmgr --version
  - ./tlmgr.sh install collection-langjapanese
  - platex -v
